services:
  db:
    image: postgres
    container_name: postgres_db
    environment: 
      - POSTGRES_DB=demodb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: . 
    command: python manage.py runserver 0.0.0.0:8000
    container_name: django_runserver
    environment:
      - DJANGO_SETTINGS_MODULE=demo.settings.local
    volumes:
      - ./demo:/demo
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  demo: