# Generated by Django 3.1.13 on 2021-08-15 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account_ops', '0003_auto_20210813_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='balance',
            new_name='internal_balance',
        ),
        migrations.RenameField(
            model_name='withdrawalrequest',
            old_name='processed',
            new_name='status',
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='account_ops.account'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_requests', to='account_ops.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
