# Generated by Django 3.1.13 on 2021-08-15 15:11
from django.db import migrations
from django.db.models import F


def forwards(apps, _):
    WithdrawalRequest = apps.get_model("account_ops", "WithdrawalRequest")
    Transaction = apps.get_model("account_ops", "Transaction")

    Transaction.objects.all().update(account_id=F("user_id"))
    WithdrawalRequest.objects.all().update(account_id=F("user_id"))


class Migration(migrations.Migration):

    dependencies = [
        ("account_ops", "0004_auto_20210815_1511"),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
