# Generated by Django 3.1.13 on 2021-08-15 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_ops', '0005_auto_20210815_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='user',
        ),
    ]
